name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 BRT == -03:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: igabb/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ 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 }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
